### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by ajthemacboy** [sjmorrow/FlickrLinkr#1]
Been looking for something like this after the website I previously used shut down... can you upload the code please?

**Comment by sjmorrow** [comment]
It's all in the dev branch: https://github.com/sjmorrow/FlickrLinkr/tree/dev

That being said, I doubt this project still works. This was from Flickr's API over 3 years ago and the concept of a "Set" in Flickr is no longer present. Give it a shot though.
